modLoader="javafml"
loaderVersion="[41,)"
issueTrackerURL="https://github.com/Vazkii/Quark"
license="https://github.com/Vazkii/Quark/blob/master/LICENSE.md"

[[mods]]
modId="quark"
displayName="Quark"
version="${file.jarVersion}"
authors="Vazkii, WireSegal, MCVinnyq, Sully"
description='''Small things, improving Minecraft bit by bit.'''

[[dependencies.quark]]
    modId="autoreglib"
    mandatory=true
    versionRange="[1.8-54,)"
    ordering="AFTER"
    side="BOTH"

[[dependencies.quark]]
    modId="forge"
    mandatory=true
    versionRange="[41.0.63,)"
    ordering="AFTER"
    side="BOTH"